// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | ExploreMoreSlice
  | IconFeatureHighlightsSlice
  | InstructionStepsWithMediaSlice
  | HeroSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *ExploreMore → Default → Primary → carousel*
 */
export interface ExploreMoreSliceDefaultPrimaryCarouselItem {
  /**
   * text field in *ExploreMore → Default → Primary → carousel*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: explore_more.default.primary.carousel[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *ExploreMore → Default → Primary*
 */
export interface ExploreMoreSliceDefaultPrimary {
  /**
   * title field in *ExploreMore → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: explore_more.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * carousel field in *ExploreMore → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: explore_more.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  carousel: prismic.GroupField<
    Simplify<ExploreMoreSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for ExploreMore Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExploreMoreSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExploreMoreSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ExploreMore*
 */
type ExploreMoreSliceVariation = ExploreMoreSliceDefault;

/**
 * ExploreMore Shared Slice
 *
 * - **API ID**: `explore_more`
 * - **Description**: ExploreMore
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExploreMoreSlice = prismic.SharedSlice<
  "explore_more",
  ExploreMoreSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Embed Up → Primary*
 */
export interface HeroSliceEmbedUpPrimary {
  /**
   * title field in *Hero → Embed Up → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.embedUp.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *Hero → Embed Up → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.embedUp.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * embed field in *Hero → Embed Up → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.embedUp.primary.embed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  embed: prismic.EmbedField;
}

/**
 * Embed Up variation for Hero Slice
 *
 * - **API ID**: `embedUp`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceEmbedUp = prismic.SharedSliceVariation<
  "embedUp",
  Simplify<HeroSliceEmbedUpPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceEmbedUp;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *IconFeatureHighlights → Default → Primary → Features*
 */
export interface IconFeatureHighlightsSliceDefaultPrimaryFeaturesItem {
  /**
   * Image field in *IconFeatureHighlights → Default → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_feature_highlights.default.primary.features[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Decorative Shape field in *IconFeatureHighlights → Default → Primary → Features*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_feature_highlights.default.primary.features[].shape
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  shape: prismic.SelectField<
    "circle" | "half-circle" | "quarter-circle" | "square" | "custom"
  >;

  /**
   * Shape Color field in *IconFeatureHighlights → Default → Primary → Features*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_feature_highlights.default.primary.features[].shape_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  shape_color: prismic.ColorField;

  /**
   * Description field in *IconFeatureHighlights → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_feature_highlights.default.primary.features[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *IconFeatureHighlights → Default → Primary*
 */
export interface IconFeatureHighlightsSliceDefaultPrimary {
  /**
   * Title field in *IconFeatureHighlights → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_feature_highlights.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Features field in *IconFeatureHighlights → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_feature_highlights.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<
    Simplify<IconFeatureHighlightsSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for IconFeatureHighlights Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays a heading and a repeatable group of highlighted features, each including an image, shape, and label.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IconFeatureHighlightsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IconFeatureHighlightsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IconFeatureHighlights*
 */
type IconFeatureHighlightsSliceVariation = IconFeatureHighlightsSliceDefault;

/**
 * IconFeatureHighlights Shared Slice
 *
 * - **API ID**: `icon_feature_highlights`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IconFeatureHighlightsSlice = prismic.SharedSlice<
  "icon_feature_highlights",
  IconFeatureHighlightsSliceVariation
>;

/**
 * Item in *InstructionStepsWithMedia → Steps with Media → Primary → Steps*
 */
export interface InstructionStepsWithMediaSliceStepsWithMediaPrimaryStepsItem {
  /**
   * step number field in *InstructionStepsWithMedia → Steps with Media → Primary → Steps*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: instruction_steps_with_media.steps_with_media.primary.steps[].step_number
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  step_number: prismic.NumberField;

  /**
   * Step Text field in *InstructionStepsWithMedia → Steps with Media → Primary → Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: instruction_steps_with_media.steps_with_media.primary.steps[].step_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  step_text: prismic.KeyTextField;

  /**
   * step image field in *InstructionStepsWithMedia → Steps with Media → Primary → Steps*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: instruction_steps_with_media.steps_with_media.primary.steps[].step_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  step_image: prismic.ImageField<never>;
}

/**
 * Primary content in *InstructionStepsWithMedia → Steps with Media → Primary*
 */
export interface InstructionStepsWithMediaSliceStepsWithMediaPrimary {
  /**
   * Title field in *InstructionStepsWithMedia → Steps with Media → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: instruction_steps_with_media.steps_with_media.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Steps field in *InstructionStepsWithMedia → Steps with Media → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: instruction_steps_with_media.steps_with_media.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  steps: prismic.GroupField<
    Simplify<InstructionStepsWithMediaSliceStepsWithMediaPrimaryStepsItem>
  >;
}

/**
 * Steps with Media variation for InstructionStepsWithMedia Slice
 *
 * - **API ID**: `steps_with_media`
 * - **Description**: Instruction steps in a numbered list with a media block alongside.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InstructionStepsWithMediaSliceStepsWithMedia =
  prismic.SharedSliceVariation<
    "steps_with_media",
    Simplify<InstructionStepsWithMediaSliceStepsWithMediaPrimary>,
    never
  >;

/**
 * Slice variation for *InstructionStepsWithMedia*
 */
type InstructionStepsWithMediaSliceVariation =
  InstructionStepsWithMediaSliceStepsWithMedia;

/**
 * InstructionStepsWithMedia Shared Slice
 *
 * - **API ID**: `instruction_steps_with_media`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InstructionStepsWithMediaSlice = prismic.SharedSlice<
  "instruction_steps_with_media",
  InstructionStepsWithMediaSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ExploreMoreSlice,
      ExploreMoreSliceDefaultPrimaryCarouselItem,
      ExploreMoreSliceDefaultPrimary,
      ExploreMoreSliceVariation,
      ExploreMoreSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceEmbedUpPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceEmbedUp,
      IconFeatureHighlightsSlice,
      IconFeatureHighlightsSliceDefaultPrimaryFeaturesItem,
      IconFeatureHighlightsSliceDefaultPrimary,
      IconFeatureHighlightsSliceVariation,
      IconFeatureHighlightsSliceDefault,
      InstructionStepsWithMediaSlice,
      InstructionStepsWithMediaSliceStepsWithMediaPrimaryStepsItem,
      InstructionStepsWithMediaSliceStepsWithMediaPrimary,
      InstructionStepsWithMediaSliceVariation,
      InstructionStepsWithMediaSliceStepsWithMedia,
    };
  }
}
